### ISSUE TITLE
Adding basic light profiles

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/GalFlow#11]
We want to add some simple light profiles like Gaussian and Sersic. including ellipticity, magnitude/flux, size,, (sersic index).
Probably in `lightprofiles.py`

We want to validate is against GalSim.

**Comment by EiffL** [comment]
Any success here :-) ?

**Comment by b-remy** [comment]
I started a little comparison here, now integrating them in GalFlow with unit tests: https://colab.research.google.com/drive/1VclQ048ZarPuoN-CGKDa-OIwVKI-htHQ?usp=sharing

The sersic profile reconstruction is not as close as the gaussian, still looking how to improve :-)

Gaussian:
![image](https://user-images.githubusercontent.com/30293694/132189602-70740a98-b003-4c5a-8696-50ab4d16d6d6.png)

Sersic (r0=5, n=2):
![image](https://user-images.githubusercontent.com/30293694/132189715-bce4e0e5-614b-4263-afa4-d7daa2a76cf9.png)

**Comment by EiffL** [comment]
I just dug through the code, I think this is how GalSim knows how much flux there is in a Sersic profile: https://github.com/GalSim-developers/GalSim/blob/6c1eb247df86ec03d1a2c9c8024fe57b1bd4a154/src/SBSersic.cpp#L332

which is used here:
https://github.com/GalSim-developers/GalSim/blob/6c1eb247df86ec03d1a2c9c8024fe57b1bd4a154/galsim/sersic.py#L251
